#!/bin/sh
#
# Autogenerated test: the feature is installed with its default options, so
# `paths` is empty and the install script has nothing to do. This runs against
# every base image in the CI matrix, so it is the guard that install.sh exits 0
# on each of them rather than a test of the chown behaviour itself. The real
# behaviour lives in the scenario tests (see scenarios.json).
#
# This test can be run with the following command (from the root of this repo)
#    devcontainer features test \
#               --features volume-permissions \
#               --base-image mcr.microsoft.com/devcontainers/base:ubuntu .

# Deliberately no `set -e`: every check should run so a failure report lists all
# the problems, not just the first one.

# Must be the first command: on alpine this installs bash and re-execs under it.
. "$(dirname "$0")/_ensure_bash.sh"

source dev-container-features-test-lib
source "$(dirname "$0")/_volume_permissions_lib.sh"

WORKSPACE="$(cd "$(dirname "$0")" && pwd)"

# Reaching this point means install.sh exited 0 during the image build and the
# container started.
check "container starts with default options" true

# With no paths configured the feature must leave the filesystem alone. The only
# directory the test harness itself puts in the workspace folder is .devcontainer.
no_directories_created() {
    local stray
    stray="$(find "$WORKSPACE" -mindepth 1 -maxdepth 1 -type d -not -name '.devcontainer')"
    if [ -n "$stray" ]; then
        echoStderr "Feature created unexpected directories: $stray"
        return 1
    fi
}
check "no directories created for empty paths" no_directories_created

check "remote user can write to the workspace folder" writable_by_remote_user "$WORKSPACE"

reportResults
